"if (humidity > 70 && temperature > 25) {"
"    if (location.toLowerCase().includes('kathmandu') || location.toLowerCase().includes('lalitpur') || location.toLowerCase().includes('bhaktapur')) {"
"        fertilizer = 'NPK, Urea, Gypsum, Compost, Vermi-compost';"
"    } else if (location.toLowerCase().includes('pokhara')) {"
"        fertilizer = 'Phosphate, NPK, Compost, Urea, Potash';"
"    } else if (location.toLowerCase().includes('biratnagar')) {"
"        fertilizer = 'Compost, NPK, Urea, Gypsum, Lime';"
"    } else if (location.toLowerCase().includes('birgunj')) {"
"        fertilizer = 'Phosphate, Urea, NPK, Potash, Lime';"
"    } else if (location.toLowerCase().includes('bharatpur') || location.toLowerCase().includes('chitwan')) {"
"        fertilizer = 'Compost, Urea, NPK, Gypsum, Potash';"
"    } else if (location.toLowerCase().includes('hetauda')) {"
"        fertilizer = 'Compost, Urea, Gypsum, NPK, Potash';"
"    } else if (location.toLowerCase().includes('janakpur')) {"
"        fertilizer = 'NPK, Urea, Phosphate, Potash, Compost';"
"    } else if (location.toLowerCase().includes('itahari')) {"
"        fertilizer = 'Compost, Urea, NPK, Potash, Phosphate';"
"    } else if (location.toLowerCase().includes('dharan')) {"
"        fertilizer = 'NPK, Phosphate, Gypsum, Urea, Lime';"
"    } else if (location.toLowerCase().includes('dhangadhi')) {"
"        fertilizer = 'Compost, NPK, Urea, Lime, Gypsum';"
"    } else if (location.toLowerCase().includes('nepalgunj')) {"
"        fertilizer = 'Compost, Urea, NPK, Potash, Lime';"
"    } else if (location.toLowerCase().includes('tulsipur')) {"
"        fertilizer = 'Compost, Urea, NPK, Phosphate, Potash';"
"    } else if (location.toLowerCase().includes('ghorahi')) {"
"        fertilizer = 'Compost, Urea, Gypsum, NPK, Potash';"
"    } else if (location.toLowerCase().includes('butwal')) {"
"        fertilizer = 'Compost, NPK, Urea, Gypsum, Phosphate';"
"    } else if (location.toLowerCase().includes('siddharthanagar')) {"
"        fertilizer = 'Compost, Urea, NPK, Potash, Phosphate';"
"    } else if (location.toLowerCase().includes('bhadrapur')) {"
"        fertilizer = 'Compost, Urea, Gypsum, NPK, Potash';"
"    } else if (location.toLowerCase().includes('damak')) {"
"        fertilizer = 'Compost, NPK, Phosphate, Potash, Gypsum';"
"    } else if (location.toLowerCase().includes('rajbiraj')) {"
"        fertilizer = 'Compost, Urea, NPK, Potash, Lime';"
"    } else {"
"        fertilizer = 'General Fertilizers: Urea, NPK, Compost, Lime';"
"    }"
"} else if (humidity > 60 && temperature > 20) {"
"    if (location.toLowerCase().includes('kathmandu') || location.toLowerCase().includes('lalitpur') || location.toLowerCase().includes('bhaktapur')) {"
"        fertilizer = 'NPK, Urea, Compost, Vermi-compost';"
"    } else if (location.toLowerCase().includes('pokhara')) {"
"        fertilizer = 'NPK, Phosphate, Urea, Lime, Potash';"
"    } else if (location.toLowerCase().includes('biratnagar')) {"
"        fertilizer = 'Compost, Urea, NPK, Phosphate, Potash';"
"    } else if (location.toLowerCase().includes('birgunj')) {"
"        fertilizer = 'NPK, Phosphate, Urea, Compost, Potash';"
"    } else if (location.toLowerCase().includes('bharatpur') || location.toLowerCase().includes('chitwan')) {"
"        fertilizer = 'Compost, NPK, Urea, Potash, Lime';"
"    } else if (location.toLowerCase().includes('hetauda')) {"
"        fertilizer = 'Compost, NPK, Gypsum, Urea, Lime';"
"    } else if (location.toLowerCase().includes('janakpur')) {"
"        fertilizer = 'NPK, Urea, Potash, Lime, Compost';"
"    } else if (location.toLowerCase().includes('itahari')) {"
"        fertilizer = 'Urea, NPK, Potash, Phosphate, Compost';"
"    } else if (location.toLowerCase().includes('dharan')) {"
"        fertilizer = 'Compost, NPK, Urea, Potash, Gypsum';"
"    } else if (location.toLowerCase().includes('dhangadhi')) {"
"        fertilizer = 'NPK, Urea, Phosphate, Gypsum, Lime';"
"    } else if (location.toLowerCase().includes('nepalgunj')) {"
"        fertilizer = 'Compost, NPK, Urea, Lime, Phosphate';"
"    } else if (location.toLowerCase().includes('tulsipur')) {"
"        fertilizer = 'NPK, Urea, Compost, Lime, Potash';"
"    } else if (location.toLowerCase().includes('ghorahi')) {"
"        fertilizer = 'Compost, NPK, Urea, Lime, Phosphate';"
"    } else if (location.toLowerCase().includes('butwal')) {"
"        fertilizer = 'Urea, NPK, Compost, Gypsum, Potash';"
"    } else if (location.toLowerCase().includes('siddharthanagar')) {"
"        fertilizer = 'NPK, Urea, Potash, Compost, Phosphate';"
"    } else if (location.toLowerCase().includes('bhadrapur')) {"
"        fertilizer = 'Compost, NPK, Urea, Potash, Lime';"
"    } else if (location.toLowerCase().includes('damak')) {"
"        fertilizer = 'NPK, Phosphate, Urea, Compost, Potash';"
"    } else if (location.toLowerCase().includes('rajbiraj')) {"
"        fertilizer = 'Compost, NPK, Urea, Lime, Potash';"
"    } else {"
"        fertilizer = 'General Fertilizers: Urea, NPK, Lime, Compost';"
"    }"
"} else if (humidity > 50 && temperature > 15) {"
"    if (location.toLowerCase().includes('kathmandu') || location.toLowerCase().includes('lalitpur') || location.toLowerCase().includes('bhaktapur')) {"
"        fertilizer = 'NPK, Urea, Lime, Phosphate';"
"    } else if (location.toLowerCase().includes('pokhara')) {"
"        fertilizer = 'Compost, NPK, Urea, Lime, Potash';"
"    } else if (location.toLowerCase().includes('biratnagar')) {"
"        fertilizer = 'Compost, NPK, Urea, Phosphate, Gypsum';"
"    } else if (location.toLowerCase().includes('birgunj')) {"
"        fertilizer = 'Compost, Urea, NPK, Lime, Potash';"
"    } else if (location.toLowerCase().includes('bharatpur') || location.toLowerCase().includes('chitwan')) {"
"        fertilizer = 'Compost, Urea, Phosphate, NPK, Potash';"
"    } else if (location.toLowerCase().includes('hetauda')) {"
"        fertilizer = 'Urea, NPK, Compost, Lime, Potash';"
"    } else if (location.toLowerCase().includes('janakpur')) {"
"        fertilizer = 'NPK, Phosphate, Urea, Lime, Potash';"
"    } else if (location.toLowerCase().includes('itahari')) {"
"        fertilizer = 'Compost, NPK, Urea, Potash, Lime';"
"    } else if (location.toLowerCase().includes('dharan')) {"
"        fertilizer = 'Compost, NPK, Phosphate, Urea, Lime';"
"    } else if (location.toLowerCase().includes('dhangadhi')) {"
"        fertilizer = 'NPK, Phosphate, Urea, Compost, Potash';"
"    } else if (location.toLowerCase().includes('nepalgunj')) {"
"        fertilizer = 'Compost, NPK, Urea, Lime, Phosphate';"
"    } else if (location.toLowerCase().includes('tulsipur')) {"
"        fertilizer = 'Compost, NPK, Phosphate, Urea, Potash';"
"    } else if (location.toLowerCase().includes('ghorahi')) {"
"        fertilizer = 'Compost, NPK, Urea, Lime, Gypsum';"
"    } else if (location.toLowerCase().includes('butwal')) {"
"        fertilizer = 'Compost, NPK, Urea, Lime, Potash';"
"    } else if (location.toLowerCase().includes('siddharthanagar')) {"
"        fertilizer = 'Compost, NPK, Urea, Lime, Phosphate';"
"    } else if (location.toLowerCase().includes('bhadrapur')) {"
"        fertilizer = 'Compost, NPK, Urea, Potash, Phosphate';"
"    } else if (location.toLowerCase().includes('damak')) {"
"        fertilizer = 'NPK, Phosphate, Urea, Lime, Potash';"
"    } else if (location.toLowerCase().includes('rajbiraj')) {"
"        fertilizer = 'Compost, NPK, Phosphate, Urea, Lime';"
"    } else {"
"        fertilizer = 'General Fertilizers: Urea, NPK, Lime, Potash';"
"    }"
"} else {"
"    fertilizer = 'General Fertilizers: Urea, NPK, Compost, Potash, Gypsum';"
"}"
